set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(TOOLCHAIN_PREFIX arm-none-eabi- CACHE STRING "ARM embedded GCC toolchain prefix")

find_program(CMAKE_C_COMPILER NAMES ${TOOLCHAIN_PREFIX}gcc REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES ${TOOLCHAIN_PREFIX}gcc REQUIRED)
find_program(CMAKE_OBJCOPY NAMES ${TOOLCHAIN_PREFIX}objcopy REQUIRED)
find_program(CMAKE_SIZE NAMES ${TOOLCHAIN_PREFIX}size REQUIRED)
find_program(CMAKE_GDB NAMES ${TOOLCHAIN_PREFIX}gdb)

set(TOOLCHAIN_LINK_LIBRARIES m CACHE STRING "Default libraries linked by the toolchain")

set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}" CACHE FILEPATH "C compiler" FORCE)
set(CMAKE_ASM_COMPILER "${CMAKE_ASM_COMPILER}" CACHE FILEPATH "ASM compiler" FORCE)
set(CMAKE_OBJCOPY "${CMAKE_OBJCOPY}" CACHE FILEPATH "objcopy" FORCE)
set(CMAKE_SIZE "${CMAKE_SIZE}" CACHE FILEPATH "size" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
